# Generated by Django 3.0.10 on 2020-09-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200922_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='submission_format',
            new_name='sample_type',
        ),
        migrations.RenameField(
            model_name='workflowdefinition',
            old_name='workflow_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workflowdefinition',
            old_name='workflow_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dnaextractionresults',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='dnaextractionresults',
            name='workflow_batch',
        ),
        migrations.RemoveField(
            model_name='workflowbatch',
            name='samples',
        ),
        migrations.AddField(
            model_name='workflowbatch',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WorkflowSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Sample')),
                ('workflow_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.WorkflowBatch')),
            ],
            options={
                'verbose_name': 'Workflow Sample',
                'verbose_name_plural': 'Workflow Samples',
            },
        ),
        migrations.AddField(
            model_name='dnaextractionresults',
            name='workflow_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.WorkflowSample'),
        ),
    ]
