# Generated by Django 3.0.10 on 2020-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_historicaldnaextractionresults_historicallab_historicalproject_historicalsample_historicalworkflowba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowdefinition',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
