# Generated by Django 3.0.10 on 2020-12-03 18:51

from django.db import migrations


def populate_labs(apps, schema_editor):
    Lab = apps.get_model('database', 'Lab')
    Lab.objects.create(lab_name='Salmonella', lab_contact='sandeep.tamber@canada.ca')
    Lab.objects.create(lab_name='VTEC', lab_contact='alex.gill@canada.ca')
    Lab.objects.create(lab_name='Parasitology', lab_contact='brent.dixon@canada.ca')
    Lab.objects.create(lab_name='Botulism', lab_contact='john.austin@canada.ca')
    Lab.objects.create(lab_name='Listeria', lab_contact='franco.pagotto@canada.ca')
    Lab.objects.create(lab_name='Vibrio', lab_contact='swapan.banerjee@canada.ca')
    Lab.objects.create(lab_name='Virology', lab_contact='neda.nasheri@canada.ca')
    Lab.objects.create(lab_name='Rapid-Diagnostics', lab_contact='nathalie.corneau@canada.ca')


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0007_auto_20201112_1702'),
    ]

    operations = [
        migrations.RunPython(populate_labs)
    ]
