# Generated by Django 3.0.10 on 2020-12-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201207_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsample',
            name='submitting_lab',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='submitting_lab',
        ),
    ]
