# Generated by Django 3.0.10 on 2020-12-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20201208_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='submitting_lab',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Lab'),
        ),
        migrations.AddField(
            model_name='sample',
            name='submitting_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Lab'),
        ),
    ]
