# Generated by Django 3.0.10 on 2020-12-08 18:22

import bmh_lims.database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20201208_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(default=bmh_lims.database.models.generate_sample_id, max_length=50),
        ),
    ]
